'''
Triangular, pentagonal, and hexagonal
Problem 45

Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

It can be verified that T(285) = P(165) = H(143) = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
'''

T = [(i * (i + 1) / 2) for i in range(1, 10)]
P = [(i * (3 * i - 1) / 2) for i in range(1, 10)]
H = list(map(float, [(i * (2 * i - 1)) for i in range(1, 1000000)]))

# i_t = (((8 * t + 1) ** 0.5) - 1) / 2
# i_p = (((24 * p + 1) ** 0.5) + 1) / 6

def i_t (t):
	return (((8 * t + 1) ** 0.5) - 1) / 2
	
def i_p (p):
	return (((24 * p + 1) ** 0.5) + 1) / 6

for i in H:
	if i_p(i) % 1.0 == 0:
		print i