CXX = g++
SRCS = getInt.cpp Critter.cpp Ant.cpp Doodlebug.cpp World.cpp main.cpp
HEADERS = getInt.hpp Critter.hpp Ant.hpp Doodlebug.hpp World.hpp

main: ${SRCS} ${HEADERS}
	${CXX} ${SRCS} -o main

clean:
	rm -f *.o main